// Code generated by github.com/qwenode/convergen
// DO NOT EDIT.

package as

import "github.com/qwenode/convergen/as/data"

func UserA_UserB(src data.UserA, arg0 int, arg1 data.UserA) (dst data.UserB) {
	dst.Username = src.Username
	dst.Age = arg0
	dst.User = arg1

	return
}
